//SearchBar
export const SEARCH_COUNTRY_REQUEST = "SEARCH_COUNTRY_REQUEST";
export const SEARCH_COUNTRY_SUCCESS = "SEARCH_COUNTRY_SUCCESS";
export const SEARCH_COUNTRY_ERROR = "SEARCH_COUNTRY_ERROR";

//Home
export const COUNTRY_REQUEST = "COUNTRY_REQUEST";
export const COUNTRY_SUCCESS = "COUNTRY_SUCCESS";
export const COUNTRY_ERROR = "COUNTRY_ERROR";

//Order
export const ORDER_BY_LETTER = "ORDER_BY_LETTER";
export const ORDER_BY_POPULATION = "ORDER_BY_POPULATION";

//Post Activity
export const POST_ACTIVITY_REQUEST = "POST_ACTIVITY_REQUEST";
export const POST_ACTIVITY_SUCCESS = "POST_ACTIVITY_SUCCESS";
export const POST_ACTIVITY_ERROR = "POST_ACTIVITY_ERROR";

//Post Favorite country
export const POST_FAVORITE_COUNTRY_REQUEST = 'POST_FAVORITE_COUNTRY_REQUEST';
export const POST_FAVORITE_COUNTRY_SUCCESS = 'POST_FAVORITE_COUNTRY_SUCCESS';
export const POST_FAVORITE_COUNTRY_ERROR = 'POST_FAVORITE_COUNTRY_ERROR';

//Delete favorite country
export const DELETE_FAVORITE_COUNTRY_REQUEST = 'DELETE_FAVORITE_COUNTRY_REQUEST';
export const DELETE_FAVORITE_COUNTRY_SUCCESS = 'DELETE_FAVORITE_COUNTRY_SUCCESS';
export const DELETE_FAVORITE_COUNTRY_ERROR = 'DELETE_FAVORITE_COUNTRY_ERROR';

//Post favority activity
export const POST_FAVORITE_ACTIVITY_REQUEST = 'POST_FAVORITE_ACTIVITY_REQUEST';
export const POST_FAVORITE_ACTIVITY_SUCCESS = 'POST_FAVORITE_ACTIVITY_SUCCESS';
export const POST_FAVORITE_ACTIVITY_ERROR = 'POST_FAVORITE_ACTIVITY_ERROR';

//Delete favority activity
export const DELETE_FAVORITE_ACTIVITY_REQUEST = 'DELETE_FAVORITE_ACTIVITY_REQUEST';
export const DELETE_FAVORITE_ACTIVITY_SUCCESS = 'DELETE_FAVORITE_ACTIVITY_SUCCESS';
export const DELETE_FAVORITE_ACTIVITY_ERROR = 'DELETE_FAVORITE_ACTIVITY_ERROR';

//Message
export const MESSAGE_REQUEST = 'MESSAGE_REQUEST';
export const MESSAGE_SUCCESS = 'MESSAGE_SUCCESS';
export const MESSAGE_ERROR = 'MESSAGE_ERROR';
