//SearchBar
export const SEARCH_COUNTRY_REQUEST = "SEARCH_COUNTRY_REQUEST";
export const SEARCH_COUNTRY_SUCCESS = "SEARCH_COUNTRY_SUCCESS";
export const SEARCH_COUNTRY_ERROR = "SEARCH_COUNTRY_ERROR";

//Home
export const COUNTRY_REQUEST = "COUNTRY_REQUEST";
export const COUNTRY_SUCCESS = "COUNTRY_SUCCESS";
export const COUNTRY_ERROR = "COUNTRY_ERROR";

//Order
export const ORDER_BY_LETTER = "ORDER_BY_LETTER";
export const ORDER_BY_POPULATION = "ORDER_BY_POPULATION";

//Post Activity
export const POST_ACTIVITY_REQUEST = "POST_ACTIVITY_REQUEST";
export const POST_ACTIVITY_SUCCESS = "POST_ACTIVITY_SUCCESS";
export const POST_ACTIVITY_ERROR = "POST_ACTIVITY_ERROR";