//SearchBar
export const SEARCH_COUNTRY_REQUEST = "SEARCH_COUNTRY_REQUEST";
export const SEARCH_COUNTRY_SUCCESS = "SEARCH_COUNTRY_SUCCESS";
export const SEARCH_COUNTRY_ERROR = "SEARCH_COUNTRY_ERROR";

//Home
export const COUNTRY_REQUEST = "COUNTRY_REQUEST";
export const COUNTRY_SUCCESS = "COUNTRY_SUCCESS";
export const COUNTRY_ERROR = "COUNTRY_ERROR";